// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: calculator.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Calc {
  public static partial class CalcService
  {
    static readonly string __ServiceName = "calc.CalcService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Calc.CalcRequest> __Marshaller_calc_CalcRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Calc.CalcRequest.Parser));
    static readonly grpc::Marshaller<global::Calc.CalcResponse> __Marshaller_calc_CalcResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Calc.CalcResponse.Parser));
    static readonly grpc::Marshaller<global::Calc.CreditCardResponse> __Marshaller_calc_CreditCardResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Calc.CreditCardResponse.Parser));

    static readonly grpc::Method<global::Calc.CalcRequest, global::Calc.CalcResponse> __Method_Calcservice = new grpc::Method<global::Calc.CalcRequest, global::Calc.CalcResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Calcservice",
        __Marshaller_calc_CalcRequest,
        __Marshaller_calc_CalcResponse);

    static readonly grpc::Method<global::Calc.CalcRequest, global::Calc.CreditCardResponse> __Method_CreditCardservice = new grpc::Method<global::Calc.CalcRequest, global::Calc.CreditCardResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreditCardservice",
        __Marshaller_calc_CalcRequest,
        __Marshaller_calc_CreditCardResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Calc.CalculatorReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CalcService</summary>
    [grpc::BindServiceMethod(typeof(CalcService), "BindService")]
    public abstract partial class CalcServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Calc.CalcResponse> Calcservice(global::Calc.CalcRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Calc.CreditCardResponse> CreditCardservice(global::Calc.CalcRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CalcService</summary>
    public partial class CalcServiceClient : grpc::ClientBase<CalcServiceClient>
    {
      /// <summary>Creates a new client for CalcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CalcServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CalcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CalcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CalcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CalcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Calc.CalcResponse Calcservice(global::Calc.CalcRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Calcservice(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Calc.CalcResponse Calcservice(global::Calc.CalcRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Calcservice, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Calc.CalcResponse> CalcserviceAsync(global::Calc.CalcRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalcserviceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Calc.CalcResponse> CalcserviceAsync(global::Calc.CalcRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Calcservice, null, options, request);
      }
      public virtual global::Calc.CreditCardResponse CreditCardservice(global::Calc.CalcRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreditCardservice(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Calc.CreditCardResponse CreditCardservice(global::Calc.CalcRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreditCardservice, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Calc.CreditCardResponse> CreditCardserviceAsync(global::Calc.CalcRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreditCardserviceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Calc.CreditCardResponse> CreditCardserviceAsync(global::Calc.CalcRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreditCardservice, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CalcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CalcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CalcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Calcservice, serviceImpl.Calcservice)
          .AddMethod(__Method_CreditCardservice, serviceImpl.CreditCardservice).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CalcServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Calcservice, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Calc.CalcRequest, global::Calc.CalcResponse>(serviceImpl.Calcservice));
      serviceBinder.AddMethod(__Method_CreditCardservice, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Calc.CalcRequest, global::Calc.CreditCardResponse>(serviceImpl.CreditCardservice));
    }

  }
}
#endregion
